version: '3.9'

services:
  timescaledb:
    # define image
    image: timescale/timescaledb-ha:pg16
    container_name: vectorscaledb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - '5555:5432'
    volumes:
# map the initdb prepare db script to :/docker-entrypoint-initdb.d/prepare_similarity_search_service_db.sql
      - ./init_db/create_similar_search_service_db.sql:/docker-entrypoint-initdb.d/prepare_similarity_search_service_db.sql