repos:
   - repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.9.5
     hooks:
        - id: ruff  # Linter
          args: [--fix]  # Ensure fixes are applied
        - id: ruff-format  # Formatter
    

   - repo: https://github.com/rubik/xenon
     rev: v0.9.0
     hooks:
        - id: xenon
          args: ['--max-absolute=B', '--max-modules=B', '--max-average=A']